# The URL the site will be built for
base_url = "https://synthesizer.garden"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# Generate rss/atom feeds
generate_feed = true
feed_filename = "rss.xml"
author = "synthesizer.garden"

taxonomies = [
    {name = "tags", feed = true}
]

[slugify]
paths = "on"
taxonomies = "on"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false

[extra]
# Put all your custom variables here
thumb_height = 1024
thumb_width = 1024
thumb_op = "fit"

[search]

include_title = true
include_path = true
include_description = true
include_content = true
include_date = true

